### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by simkil** [dicebear/api#4]
When trying to run docker image error occurse:

/dicebear-api/versions/5.0/index.ts:4
const routes = [
               ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /dicebear-api/node_modules/@dicebear/core/lib/index.js from /dicebear-api/versions/5.0/index.ts not supported.
Instead change the require of index.js in /dicebear-api/versions/5.0/index.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/dicebear-api/versions/5.0/index.ts:4:16)
    at Module.m._compile (/dicebear-api/node_modules/ts-node/dist/index.js:735:29)
    at Object.require.extensions.<computed> [as .ts] (/dicebear-api/node_modules/ts-node/dist/index.js:737:16)
    at /dicebear-api/config.ts:20:84 {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by FlorianKoerner** [comment]
Error should be fixed. Please let me know if not.
