### ISSUE TITLE
Difficulty compiling to javascript for use on AWS Lambda

### ISSUE THREAD

**Issue by selfsimilar** [dicebear/api#7]
I want to self-host this project on the AWS Lambda serverless service. Hosting on serverless is not a new thought, given your own [Dicebears Serverless repo](https://github.com/dicebear/serverless). But since that is both deprecated and out of date (and targeting the Cloudflare serverless platform), I thought the easiest thing would be to try to adapt this code base instead. My plan is to use the [aws-lambda-fastify](https://github.com/fastify/aws-lambda-fastify) project and create a new entry point that then calls into the current app.

But since AWS Lambda natively runs Node, I thought it would be better to just straight compile this project to JS, then add the aws-lambda-fastly wrapper. However, I cannot get this project to run once compiled to JS.

I created a new file in the root - `tsconfig.awslambda.json` with the following contents:

```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "display": "Node 16",
  "$schema": "https://json.schemastore.org/tsconfig",

  "compilerOptions": {
    "lib": ["es2021"],
    "module": "commonjs",
    "target": "es2020",

    "strict": true,
    "preserveConstEnums": true,
    "sourceMap": false,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "isolatedModules": true,

    "outDir": "dist"
  },
  "exclude": ["node_modules", "**/*.test.ts"]
}
```

Then I run `tsc --project tsconfig.awslambda.json`, which compiles cleanly. This compiles everything to the `dist` directory. But I get the following error when I run `node dist/app/src/index.js`:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/@dicebear/converter/lib/node/index.js from dist/app/src/actions/avatar.js not supported.
Instead change the require of index.js in dist/app/src/actions/avatar.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (dist/app/src/actions/avatar.js:35:21)
    at Object.<anonymous> (dist/app/src/routes.js:7:37)
    at Object.<anonymous> (dist/app/src/core.js:33:37)
    at Object.<anonymous> (dist/app/src/index.js:6:19) {
  code: 'ERR_REQUIRE_ESM'
}
```

I can resolve this error by changing the `require` to an `import` (though obviously I'd like to avoid changing the JS after running `tsc`). However, now running `node dist/app/src/index.js` gives the following error:

```
versions/4.5/index.ts:1
import Avatars from '@dicebear/avatars';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at dist/app/config.js:29:105
```

Unfortunately, I'm not very familiar with the Typescript ecosystem, so I might be doing something obviously wrong and not know it. Any help in the above problem would be appreciated. Or more generally, if there's a better way to self-host this on  Lambda, I'd love to hear it.

Thanks

**Comment by selfsimilar** [comment]
On further review, I think the newer error is because somehow the require statement in `dist/app/config.js:29:105` is resolving to outside the `dist` directory - `versions/4.5/package.json` which references `index.ts`. `config.js` line 29 is:

```
(0, env_js_1.env)('ENABLE_VERSION_4_5', '1') && versions.push(Promise.resolve().then(() => __importStar(require('@dicebear/api-4.5'))));
```

Maybe this is because the root `package.json` defines multiple packages in the workspace and `tsc` is not updating all the references properly?
